spring.application.name=demo_jdbc_crud
spring.profiles.active=jdbc
server.port = 3306

spring.datasource.url=jdbc:mysql://172.17.34.40:3306/reservas_lacanal
spring.datasource.username=adminreservas
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver