services:
  db-la-canal:
    image: mariadb:latest
    container_name: db-la-canal
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: la-canal-admin
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  book-api:
    build:
      context: ../book_api
      dockerfile: Dockerfile
    container_name: book-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db-la-canal
      - DB_PORT=3306
    depends_on:
      db-la-canal:
        condition: service_healthy

volumes:
  db_data: