spring.application.name=book_api
spring.profiles.active=jdbc
server.port=8080

spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:3306/reservas_lacanal
spring.datasource.username=reservasadmin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect